#!/usr/bin/env python
# -*- coding:utf-8 -*-

import re

def waf_wordfence(*_):
	'''Wordfence (Feedjit)'''
	if re.search(r'This response was generated by Wordfence|Your access to this site has been limited',
		_[1] or '',re.I): return waf_wordfence.__doc__