#!/usr/bin/env python
# -*- coding:utf-8 -*-

import re

def waf_modsecurity(*_):
	'''ModSecurity: Open Source Web Application Firewall (Trustwave)'''
	for item in _[0].items():
		if re.search(r'Mod_Security|NOYB',item[1] or '',re.I):
			return waf_modsecurity.__doc__
	if any(_ in _[1] for _ in  ("This error was generated by Mod_Security", "One or more things in your request were suspicious",
		"rules of the mod_security module")): return waf_modsecurity.__doc__